/**
 * Ahmet's Turkish textbook. Units are homework; pages are read pages, memory cards
 * (keyword method: a Turkish word linked to a similar-sounding English word and a funny
 * picture) or exercises that reuse the dialogue activities (choice, listen, order, speak).
 */
export const TEXTBOOK = {
  units: [
    {
      id: 'u1', title: 'Ünite 1: Ailem', titleEn: 'Unit 1: My family',
      pages: [
        {
          type: 'read', title: 'Ailem',
          lines: [
            ['Benim adım Ahmet.', 'My name is Ahmet.'],
            ['Ben on yaşındayım.', 'I am ten years old.'],
            ['Annemin adı Ayşe.', "My mother's name is Ayşe."],
            ['Babamın adı Mehmet.', "My father's name is Mehmet."],
            ['Dedemin adı Hüseyin.', "My grandfather's name is Hüseyin."],
            ['Biz köyde yaşıyoruz.', 'We live in a village.'],
          ],
          words: [['köy', 'village'], ['yaşamak', 'to live'], ['aile', 'family']],
        },
        {
          type: 'memory', title: 'Fil hafızası 🐘',
          cards: [
            { tr: 'süt', en: 'milk', sounds: '“suit”', picture: 'Takım elbise (suit) giymiş bir süt şişesi.', ar: { sounds: '«سوط»', picture: 'زجاجة حليب تلوّح بسوط.' }, ur: { sounds: '«سوٹ»', picture: 'دودھ کی بوتل نے سوٹ پہن رکھا ہے۔' }, es: { sounds: '«su té»', picture: 'Una botella de leche se toma su té.' }, fr: { sounds: '«suite»', picture: 'Une bouteille de lait dort dans une suite d’hôtel.' } },
            { tr: 'kova', en: 'bucket', sounds: '“cover”', picture: 'Kovanın üstünde kocaman bir kapak (cover).', ar: { sounds: '«قهوة»', picture: 'دلو مملوء بالقهوة الساخنة.' }, ur: { sounds: '«کوا»', picture: 'ایک کوا بالٹی میں بیٹھا ہے۔' }, es: { sounds: '«cueva»', picture: 'Un cubo gigante sale de una cueva.' }, fr: { sounds: '«couvert»', picture: 'Un seau rempli de couverts : couteaux et fourchettes.' } },
            { tr: 'kapı', en: 'door', sounds: '“copy”', picture: 'Fotokopi makinesi (copy) gibi kapı, açıldıkça kopyalar basıyor.', ar: { sounds: '«كاب»', picture: 'باب يلبس كاباً (قبعة) كبيراً.' }, ur: { sounds: '«کاپی»', picture: 'دروازے پر ایک کاپی چپکی ہوئی ہے۔' }, es: { sounds: '«capa»', picture: 'Una puerta lleva una capa de superhéroe.' }, fr: { sounds: '«capot»', picture: 'Une porte avec un capot de voiture.' } },
            { tr: 'kitap', en: 'book', sounds: '“kit up”', picture: 'Bir kitap, sırt çantasıyla yolculuğa hazırlanıyor (kit up).', ar: { sounds: '«كتاب»', picture: 'تقريباً نفس الكلمة! كتاب ← kitap.' }, ur: { sounds: '«کتاب»', picture: 'تقریباً وہی لفظ! کتاب ← kitap' }, es: { sounds: '«quita la tapa»', picture: 'Un libro quita la tapa de una olla.' }, fr: { sounds: '«qui tape»', picture: 'Un livre qui tape à la machine à écrire.' } },
            { tr: 'ev', en: 'house', sounds: '“Eve”', picture: 'Eve adında bir kız evin kapısında el sallıyor.', ar: { sounds: '«أيوه»', picture: 'بيت يهزّ رأسه ويقول: أيوه!' }, ur: { sounds: '«ایوان»', picture: 'چھوٹا سا گھر ایک بڑا ایوان بن گیا۔' }, es: { sounds: '«Eva»', picture: 'Eva saluda desde la puerta de su casa.' }, fr: { sounds: '«Ève»', picture: 'Ève fait coucou devant sa maison.' } },
          ],
        },
        { type: 'exercise', title: 'Soru 1', activity: 'choice', say: 'Ahmet\'in annesinin adı ne?', en: "What is Ahmet's mother's name?", hint: 'Annemin adı …',
          options: [{ tr: 'Elif', en: '', wrong: true }, { tr: 'Ayşe', en: '' }, { tr: 'Zeynep', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 2', activity: 'order', say: 'Cümleyi kur.', en: 'Build the sentence.', answer: 'Biz köyde yaşıyoruz.', answerEn: 'We live in a village.' },
        { type: 'exercise', title: 'Soru 3', activity: 'listen', say: 'Dedemin adı Hüseyin.', en: "My grandfather's name is Hüseyin.", prompt: 'Ne duydun?', speaker: 'dede',
          options: [{ tr: 'Babamın adı Hüseyin.', en: '', wrong: true }, { tr: 'Dedemin adı Hüseyin.', en: '' }, { tr: 'Dedemin adı Mehmet.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 4', activity: 'choice', say: 'Boşluğu doldur: “Ben on yaş___ım.”', en: 'Fill the gap: “I am ten years old.”', hint: 'yaşındayım = I am … years old',
          options: [{ tr: 'ında', en: '' }, { tr: 'da', en: '', wrong: true }, { tr: 'ın', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 5', activity: 'speak', say: 'Sesli oku:', en: 'Read aloud:', expect: ['Benim adım Ahmet', 'Ben on yaşındayım'], show: 'Benim adım Ahmet. Ben on yaşındayım.' },
        { type: 'exercise', title: 'Soru 6', activity: 'choice', optionsAreMeanings: true, say: '“süt” ne demek?', en: 'What does “süt” mean?', hint: 'süt = milk',
          options: [{ tr: 'milk', en: '' }, { tr: 'suit', en: '', wrong: true }, { tr: 'water', en: '', wrong: true }] },
      ],
    },
    {
      id: 'u2', title: 'Ünite 2: Sayılar', titleEn: 'Unit 2: Numbers', reward: 2,
      pages: [
        {
          type: 'read', title: 'Sayılar',
          lines: [
            ['Bir, iki, üç, dört, beş.', 'One, two, three, four, five.'],
            ['Altı, yedi, sekiz, dokuz, on.', 'Six, seven, eight, nine, ten.'],
            ['Benim iki elim var.', 'I have two hands.'],
            ['Bir elde beş parmak var.', 'There are five fingers on one hand.'],
            ['Sınıfta on öğrenci var.', 'There are ten students in the class.'],
            ['Elmanın kilosu otuz lira.', 'A kilo of apples is thirty lira.'],
          ],
          words: [['sayı', 'number'], ['parmak', 'finger'], ['kaç?', 'how many?'], ['otuz', 'thirty']],
        },
        {
          type: 'memory', title: 'Fil hafızası 🐘',
          cards: [
            { tr: 'iki', en: 'two', sounds: '“icky”', picture: 'İki tane yapış yapış (icky) sakız.', ar: { sounds: '«يكفي»', picture: 'طفل يأكل قطعتين ويقول: يكفي!' }, ur: { sounds: '«اِکّا»', picture: 'دو اِکّے (تانگے) ایک ساتھ دوڑ رہے ہیں۔' }, es: { sounds: '«¿y qué?»', picture: 'Dos niños dicen a la vez: «¿y qué?»' }, fr: { sounds: '«hic !»', picture: 'Deux hoquets d’affilée : hic ! hic !' } },
            { tr: 'üç', en: 'three', sounds: '“ouch”', picture: 'Üç arı sokuyor: ouch, ouch, ouch!', ar: { sounds: '«أوج»', picture: 'ثلاثة متسلقين على أوج الجبل.' }, ur: { sounds: '«اونچ»', picture: 'تین بچے اونچی دیوار پر بیٹھے ہیں۔' }, es: { sounds: '«hucha»', picture: 'Tres monedas caen en la hucha.' }, fr: { sounds: '«huche»', picture: 'Trois pains dans la huche à pain.' } },
            { tr: 'beş', en: 'five', sounds: '“bash”', picture: 'Beş parmaklı kocaman bir el: bash!', ar: { sounds: '«بشّ»', picture: 'خمسة أصابع تلوّح ببشاشة.' }, ur: { sounds: '«بیش»', picture: 'پانچ، چار سے بیش (زیادہ) ہے۔' }, es: { sounds: '«beso»', picture: 'Cinco besos en la mejilla.' }, fr: { sounds: '«bêche»', picture: 'Cinq bêches plantées dans le jardin.' } },
            { tr: 'on', en: 'ten', sounds: '“on”', picture: 'On lambanın hepsi “on” (açık).', ar: { sounds: '«عَون»', picture: 'عشرة أشخاص جاؤوا للعون.' }, ur: { sounds: '«اون»', picture: 'اون کے دس گولے۔' }, es: { sounds: '«Honda»', picture: 'Diez coches Honda en fila.' }, fr: { sounds: '«on»', picture: '« On est dix ! » crient dix enfants.' } },
          ],
        },
        { type: 'exercise', title: 'Soru 1', activity: 'choice', say: 'Üç artı dört kaç eder?', en: 'What is three plus four?', hint: 'yedi = seven',
          options: [{ tr: 'Sekiz.', en: '', wrong: true }, { tr: 'Yedi.', en: '' }, { tr: 'Altı.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 2', activity: 'listen', say: 'Sınıfta on öğrenci var.', en: 'There are ten students in the class.', prompt: 'Ne duydun?', speaker: 'ogretmen',
          options: [{ tr: 'Sınıfta beş öğrenci var.', en: '', wrong: true }, { tr: 'Sınıfta on öğrenci var.', en: '' }, { tr: 'Bahçede on kedi var.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 3', activity: 'order', say: 'Cümleyi kur.', en: 'Build the sentence.', answer: 'Benim iki elim var.', answerEn: 'I have two hands.' },
        { type: 'exercise', title: 'Soru 4', activity: 'choice', optionsAreMeanings: true, say: '“dokuz” ne demek?', en: 'What does “dokuz” mean?', hint: 'dokuz = 9',
          options: [{ tr: 'eight', en: '', wrong: true }, { tr: 'nineteen', en: '', wrong: true }, { tr: 'nine', en: '' }] },
        { type: 'exercise', title: 'Soru 5', activity: 'choice', say: 'Bir elde kaç parmak var?', en: 'How many fingers are there on one hand?', hint: 'Bir elde beş parmak var.',
          options: [{ tr: 'Beş parmak var.', en: '' }, { tr: 'On parmak var.', en: '', wrong: true }, { tr: 'İki parmak var.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 6', activity: 'speak', say: 'Sesli say:', en: 'Count out loud:', expect: ['Bir iki üç dört beş'], show: 'Bir, iki, üç, dört, beş.' },
      ],
    },
    {
      id: 'u3', title: 'Ünite 3: Okulum', titleEn: 'Unit 3: My school', reward: 2,
      pages: [
        {
          type: 'read', title: 'Okulum',
          lines: [
            ['Benim okulum köyde.', 'My school is in the village.'],
            ['Öğretmenimin adı Zeynep.', "My teacher's name is Zeynep."],
            ['Sınıfta masa, sandalye ve tahta var.', 'In the classroom there are desks, chairs and a board.'],
            ['Çantamda kitap, defter ve kalem var.', 'In my bag there are a book, a notebook and a pencil.'],
            ['Teneffüste bahçede top oynarız.', 'At break we play ball in the yard.'],
            ['Ders bitince eve dönerim.', 'When the lesson ends, I go home.'],
          ],
          words: [['okul', 'school'], ['öğretmen', 'teacher'], ['teneffüs', 'break (between lessons)'], ['tahta', 'board']],
        },
        {
          type: 'memory', title: 'Fil hafızası 🐘',
          cards: [
            { tr: 'kalem', en: 'pencil', sounds: '“call ’em”', picture: 'Bir kalem telefonla herkesi arıyor: call ’em!', ar: { sounds: '«قلم»', picture: 'تقريباً نفس الكلمة! قلم ← kalem.' }, ur: { sounds: '«قلم»', picture: 'تقریباً وہی لفظ! قلم ← kalem' }, es: { sounds: '«calamar»', picture: 'Un calamar escribe con un lápiz.' }, fr: { sounds: '«calme»', picture: 'Un crayon très calme fait du yoga.' } },
            { tr: 'defter', en: 'notebook', sounds: '“daft hair”', picture: 'Defterin kapağında çılgın saçlı (daft hair) bir adam.', ar: { sounds: '«دفتر»', picture: 'نفس الكلمة! دفتر ← defter.' }, ur: { sounds: '«دفتر»', picture: 'ایک دفتر جس میں ہر طرف کاپیاں ہیں۔' }, es: { sounds: '«de fiesta»', picture: 'Un cuaderno de fiesta con gorro y globos.' }, fr: { sounds: '«dé, terre»', picture: 'Un dé roule sur un cahier posé par terre.' } },
            { tr: 'masa', en: 'table', sounds: '“massage”', picture: 'Masaya masaj (massage) yapılıyor.', ar: { sounds: '«ماسة»', picture: 'طاولة عليها ماسة لامعة.' }, ur: { sounds: '«مسالا»', picture: 'میز پر مسالے ہی مسالے۔' }, es: { sounds: '«masa»', picture: 'Una mesa llena de masa de pan.' }, fr: { sounds: '«masser»', picture: 'Une table qui se fait masser.' } },
            { tr: 'okul', en: 'school', sounds: '“oh, cool”', picture: 'Okulu gören çocuk: “Oh, cool!”', ar: { sounds: '«أكول»', picture: 'تلميذ أكول يأكل طوال الوقت في المدرسة.' }, ur: { sounds: '«او، کول!»', picture: 'اسکول دیکھ کر بچہ بولا: او، کول!' }, es: { sounds: '«oculista»', picture: 'Un oculista revisa los ojos de toda la escuela.' }, fr: { sounds: '«oh, cool !»', picture: 'Un élève voit l’école : « Oh, cool ! »' } },
          ],
        },
        { type: 'exercise', title: 'Soru 1', activity: 'choice', say: 'Öğretmenin adı ne?', en: "What is the teacher's name?", hint: 'Öğretmenimin adı …',
          options: [{ tr: 'Elif', en: '', wrong: true }, { tr: 'Zeynep', en: '' }, { tr: 'Ayşe', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 2', activity: 'order', say: 'Cümleyi kur.', en: 'Build the sentence.', answer: 'Çantamda kitap ve kalem var.', answerEn: 'In my bag there is a book and a pencil.' },
        { type: 'exercise', title: 'Soru 3', activity: 'listen', say: 'Teneffüste bahçede top oynarız.', en: 'At break we play ball in the yard.', prompt: 'Ne duydun?', speaker: 'ogretmen',
          options: [{ tr: 'Teneffüste sınıfta uyuruz.', en: '', wrong: true }, { tr: 'Akşam bahçede top oynarız.', en: '', wrong: true }, { tr: 'Teneffüste bahçede top oynarız.', en: '' }] },
        { type: 'exercise', title: 'Soru 4', activity: 'choice', optionsAreMeanings: true, say: '“teneffüs” ne demek?', en: 'What does “teneffüs” mean?', hint: 'Teneffüste bahçede oynarız.',
          options: [{ tr: 'break (between lessons)', en: '' }, { tr: 'lesson', en: '', wrong: true }, { tr: 'teacher', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 5', activity: 'choice', say: 'Boşluğu doldur: “Okul___ köyde.” (my school)', en: 'Fill the gap: “My school is in the village.”', hint: 'okulum = my school',
          options: [{ tr: 'um', en: '' }, { tr: 'lar', en: '', wrong: true }, { tr: 'dan', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 6', activity: 'speak', say: 'Sesli oku:', en: 'Read aloud:', expect: ['Benim okulum köyde', 'Okulum köyde'], show: 'Benim okulum köyde.' },
      ],
    },
    {
      id: 'u4', title: 'Ünite 4: Evim ve yemekler', titleEn: 'Unit 4: My home and food', reward: 2,
      pages: [
        {
          type: 'read', title: 'Evimiz',
          lines: [
            ['Bizim evimiz küçük ama sıcak.', 'Our house is small but warm.'],
            ['Mutfakta annem yemek yapıyor.', 'Mom is cooking in the kitchen.'],
            ['Kahvaltıda peynir, zeytin ve ekmek yeriz.', 'At breakfast we eat cheese, olives and bread.'],
            ['Akşam yemeğinde sıcak çorba içeriz.', 'At dinner we have hot soup.'],
            ['Yemekten önce ellerimizi yıkarız.', 'Before eating we wash our hands.'],
            ['Afiyet olsun!', 'Enjoy your meal!'],
          ],
          words: [['mutfak', 'kitchen'], ['kahvaltı', 'breakfast'], ['çorba', 'soup'], ['afiyet olsun', 'enjoy your meal']],
        },
        {
          type: 'memory', title: 'Fil hafızası 🐘',
          cards: [
            { tr: 'peynir', en: 'cheese', sounds: '“pay near”', picture: 'Peyniri almak için yakında (near) para öde (pay).', ar: { sounds: '«بين النار»', picture: 'جبنة تذوب بين النار.' }, ur: { sounds: '«پنیر»', picture: 'تقریباً وہی لفظ! پنیر ← peynir' }, es: { sounds: '«peinar»', picture: 'Un queso se peina el pelo.' }, fr: { sounds: '«peinture»', picture: 'Un fromage fait de la peinture.' } },
            { tr: 'çorba', en: 'soup', sounds: '“chore-ba”', picture: 'Çorba pişirmek bir ev işi (chore).', ar: { sounds: '«شوربة»', picture: 'نفس الكلمة! شوربة ← çorba.' }, ur: { sounds: '«شوربہ»', picture: 'وہی لفظ! شوربہ ← çorba' }, es: { sounds: '«sorbo»', picture: 'Sorbo a sorbo me tomo la sopa.' }, fr: { sounds: '«sorbet»', picture: 'Une soupe chaude servie dans un pot de sorbet.' } },
            { tr: 'zeytin', en: 'olive', sounds: '“say tin”', picture: 'Zeytinler teneke (tin) kutuda.', ar: { sounds: '«زيتون»', picture: 'تقريباً نفس الكلمة! زيتون ← zeytin.' }, ur: { sounds: '«زیتون»', picture: 'وہی لفظ! زیتون ← zeytin' }, es: { sounds: '«aceituna»', picture: 'Las dos palabras vienen del árabe az-zaytūna.' }, fr: { sounds: '«satin»', picture: 'Une olive en robe de satin.' } },
            { tr: 'mutfak', en: 'kitchen', sounds: '“mutt fork”', picture: 'Mutfakta bir köpek (mutt) çatal (fork) tutuyor.', ar: { sounds: '«مطبخ»', picture: 'قريبة من «مطبخ»: matbah ← mutfak.' }, ur: { sounds: '«مطبخ»', picture: 'عربی «مطبخ» جیسا: باورچی خانہ' }, es: { sounds: '«muy flaco»', picture: 'Un cocinero muy flaco en la cocina.' }, fr: { sounds: '«muet facteur»', picture: 'Un facteur muet mange dans la cuisine.' } },
          ],
        },
        { type: 'exercise', title: 'Soru 1', activity: 'choice', say: 'Annem nerede yemek yapıyor?', en: 'Where is mom cooking?', hint: 'mutfak = kitchen',
          options: [{ tr: 'Bahçede.', en: '', wrong: true }, { tr: 'Mutfakta.', en: '' }, { tr: 'Okulda.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 2', activity: 'order', say: 'Cümleyi kur.', en: 'Build the sentence.', answer: 'Akşam yemeğinde çorba içeriz.', answerEn: 'At dinner we have soup.' },
        { type: 'exercise', title: 'Soru 3', activity: 'listen', say: 'Kahvaltıda peynir ve zeytin yeriz.', en: 'At breakfast we eat cheese and olives.', prompt: 'Ne duydun?', speaker: 'anne',
          options: [{ tr: 'Kahvaltıda peynir ve zeytin yeriz.', en: '' }, { tr: 'Kahvaltıda çorba ve pilav yeriz.', en: '', wrong: true }, { tr: 'Akşam peynir ve zeytin yeriz.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 4', activity: 'choice', optionsAreMeanings: true, say: '“afiyet olsun” ne demek?', en: 'What does “afiyet olsun” mean?', hint: 'Yemekte söyleriz.',
          options: [{ tr: 'good night', en: '', wrong: true }, { tr: 'enjoy your meal', en: '' }, { tr: 'thank you', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 5', activity: 'choice', say: 'Yemekten önce ne yaparız?', en: 'What do we do before eating?', hint: 'Yemekten önce ellerimizi yıkarız.',
          options: [{ tr: 'Televizyon izleriz.', en: '', wrong: true }, { tr: 'Uyuruz.', en: '', wrong: true }, { tr: 'Ellerimizi yıkarız.', en: '' }] },
        { type: 'exercise', title: 'Soru 6', activity: 'speak', say: 'Sesli söyle:', en: 'Say it out loud:', expect: ['Afiyet olsun'], show: 'Afiyet olsun!' },
      ],
    },
    {
      id: 'u5', title: 'Ünite 5: Günüm', titleEn: 'Unit 5: My day', reward: 2,
      pages: [
        {
          type: 'read', title: 'Bir günüm',
          lines: [
            ['Sabah saat yedide kalkarım.', 'In the morning I get up at seven.'],
            ['Yüzümü yıkar, dişlerimi fırçalarım.', 'I wash my face and brush my teeth.'],
            ['Saat sekizde okula giderim.', 'At eight I go to school.'],
            ['Öğleden sonra ödevimi yaparım.', 'In the afternoon I do my homework.'],
            ['Akşam ailemle yemek yerim.', 'In the evening I eat with my family.'],
            ['Gece saat dokuzda uyurum.', 'At night I go to sleep at nine.'],
          ],
          words: [['sabah', 'morning'], ['öğleden sonra', 'afternoon'], ['akşam', 'evening'], ['gece', 'night'], ['saat', 'hour, clock']],
        },
        {
          type: 'memory', title: 'Fil hafızası 🐘',
          cards: [
            { tr: 'saat', en: 'clock, hour', sounds: '“sat”', picture: 'Kocaman bir saat sandalyede oturuyor (sat).', ar: { sounds: '«ساعة»', picture: 'نفس الكلمة! ساعة ← saat.' }, ur: { sounds: '«ساعت»', picture: 'وہی لفظ! ساعت ← saat' }, es: { sounds: '«saeta»', picture: 'Un reloj con una saeta (flecha) en vez de aguja.' }, fr: { sounds: '«sa tête»', picture: 'Une horloge posée sur sa tête.' } },
            { tr: 'sabah', en: 'morning', sounds: '“sub, ah!”', picture: 'Sabah denizaltı (sub) suyun üstüne çıkıyor: Ah!', ar: { sounds: '«صباح»', picture: 'نفس الكلمة! صباح ← sabah.' }, ur: { sounds: '«صبح»', picture: 'تقریباً وہی لفظ! صبح ← sabah' }, es: { sounds: '«sábana»', picture: 'Por la mañana salgo de la sábana.' }, fr: { sounds: '«ça bat»', picture: 'Le matin, mon réveil, ça bat fort !' } },
            { tr: 'akşam', en: 'evening', sounds: '“ox, sham(poo)”', picture: 'Akşam bir öküz (ox) şampuanla yıkanıyor.', ar: { sounds: '«آه، شام»', picture: 'مساءٌ جميل في الشام: آه!' }, ur: { sounds: '«اک شام»', picture: 'اک شام = ایک شام! akşam' }, es: { sounds: '«a ese jamón»', picture: 'Por la tarde vamos a ese jamón para cenar.' }, fr: { sounds: '«ah, champ»', picture: 'Le soir : ah, que les champs sont beaux !' } },
            { tr: 'gece', en: 'night', sounds: '“get-cha”', picture: 'Gece bir canavar: “I’ll getcha!”', ar: { sounds: '«دجاجة»', picture: 'دجاجة نائمة في الليل.' }, ur: { sounds: '«گاجر»', picture: 'رات کو ایک گاجر سو رہی ہے۔' }, es: { sounds: '«leche»', picture: 'Un vaso de leche antes de dormir por la noche.' }, fr: { sounds: '«gâché»', picture: 'Une nuit gâchée par un moustique.' } },
          ],
        },
        { type: 'exercise', title: 'Soru 1', activity: 'choice', say: 'Metne göre: Sabah saat kaçta kalkarım?', en: 'According to the text: at what time do I get up in the morning?', hint: 'Sabah saat yedide kalkarım.',
          options: [{ tr: 'Yedide.', en: '' }, { tr: 'On ikide.', en: '', wrong: true }, { tr: 'Dokuzda.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 2', activity: 'order', say: 'Cümleyi kur.', en: 'Build the sentence.', answer: 'Saat sekizde okula giderim.', answerEn: 'At eight I go to school.' },
        { type: 'exercise', title: 'Soru 3', activity: 'choice', optionsAreMeanings: true, say: '“öğleden sonra” ne demek?', en: 'What does “öğleden sonra” mean?', hint: 'öğle = noon, sonra = after',
          options: [{ tr: 'morning', en: '', wrong: true }, { tr: 'afternoon', en: '' }, { tr: 'midnight', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 4', activity: 'listen', say: 'Gece saat dokuzda uyurum.', en: 'At night I go to sleep at nine.', prompt: 'Ne duydun?', speaker: 'anne',
          options: [{ tr: 'Gece saat onda uyurum.', en: '', wrong: true }, { tr: 'Sabah saat dokuzda kalkarım.', en: '', wrong: true }, { tr: 'Gece saat dokuzda uyurum.', en: '' }] },
        { type: 'exercise', title: 'Soru 5', activity: 'choice', say: 'Hangisi doğru?', en: 'Which one is correct?', hint: 'dişlerimi = my teeth (object)',
          options: [{ tr: 'Dişlerim fırçalarım.', en: '', wrong: true }, { tr: 'Dişlerimi fırçalarım.', en: '' }, { tr: 'Dişlerimi fırçalar ben.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 6', activity: 'speak', say: 'Sesli oku:', en: 'Read aloud:', expect: ['Sabah saat yedide kalkarım'], show: 'Sabah saat yedide kalkarım.' },
      ],
    },
    {
      id: 'u6', title: 'Ünite 6: Köyde alışveriş', titleEn: 'Unit 6: Shopping in the village', reward: 2,
      pages: [
        {
          type: 'read', title: 'Bakkalda',
          lines: [
            ['Bakkala gidip ekmek alırım.', 'I go to the grocer and buy bread.'],
            ['— Merhaba, bir ekmek lütfen.', '— Hello, one bread please.'],
            ['— Buyurun. Başka bir şey?', '— Here you are. Anything else?'],
            ['— Bir de süt. Ne kadar?', '— And some milk. How much is it?'],
            ['— Toplam yirmi lira.', '— Twenty lira in total.'],
            ['— Teşekkürler, iyi günler!', '— Thanks, have a nice day!'],
          ],
          words: [['lütfen', 'please'], ['ne kadar?', 'how much?'], ['buyurun', 'here you are'], ['toplam', 'total']],
        },
        {
          type: 'memory', title: 'Fil hafızası 🐘',
          cards: [
            { tr: 'para', en: 'money', sounds: '“pair-a”', picture: 'Bir çift (pair) bozuk para.', ar: { sounds: '«بارة»', picture: '«البارة» عملة عثمانية قديمة!' }, ur: { sounds: '«پارہ»', picture: 'پارے جیسے چمکتے سکے۔' }, es: { sounds: '«para»', picture: 'Dinero para todo.' }, fr: { sounds: '«parapluie»', picture: 'Une pluie de pièces sous un parapluie.' } },
            { tr: 'ucuz', en: 'cheap', sounds: '“oo, juice!”', picture: 'Meyve suyu çok ucuz: “Oo, juice!”', ar: { sounds: '«عجوز»', picture: 'عجوز تشتري أشياء رخيصة.' }, ur: { sounds: '«او، جوس!»', picture: 'جوس بہت سستا ہے: او، جوس!' }, es: { sounds: '«¡uy, jugos!»', picture: '¡Uy, jugos baratos!' }, fr: { sounds: '«ouh, jus !»', picture: 'Ouh, du jus pas cher !' } },
            { tr: 'pahalı', en: 'expensive', sounds: '“pa’s hall”', picture: 'Babam (pa) koca bir salon (hall) almış: çok pahalı!', ar: { sounds: '«باهظ»', picture: 'قريبة من «باهظ»: غالٍ جداً!' }, ur: { sounds: '«پہاڑی»', picture: 'پہاڑ جیسی اونچی قیمت!' }, es: { sounds: '«pa’ allí»', picture: '¡Tan caro que me voy pa’ allí!' }, fr: { sounds: '«pas à lui»', picture: 'C’est trop cher, ce n’est pas à lui !' } },
            { tr: 'lütfen', en: 'please', sounds: '“loot fan”', picture: 'Bir hayran (fan) ganimet (loot) istiyor: lütfen!', ar: { sounds: '«لطفاً»', picture: 'تقريباً نفس الكلمة! لطفاً ← lütfen.' }, ur: { sounds: '«لطف»', picture: 'لطف و مہربانی سے: lütfen' }, es: { sounds: '«¡Lupe, ven!»', picture: '—¡Lupe, ven, por favor!' }, fr: { sounds: '«lutin»', picture: 'Un lutin dit poliment : s’il te plaît !' } },
          ],
        },
        { type: 'exercise', title: 'Soru 1', activity: 'choice', say: 'Bakkalda ne dersin?', en: "What do you say at the grocer's?", hint: '… lütfen.',
          options: [{ tr: 'İyi geceler, anne.', en: '', wrong: true }, { tr: 'Bir ekmek lütfen.', en: '' }, { tr: 'Ben on yaşındayım.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 2', activity: 'order', say: 'Cümleyi kur.', en: 'Build the sentence.', answer: 'Bir ekmek ve bir süt lütfen.', answerEn: 'One bread and one milk, please.' },
        { type: 'exercise', title: 'Soru 3', activity: 'listen', say: 'Toplam yirmi lira.', en: 'Twenty lira in total.', prompt: 'Ne duydun?', speaker: 'bakkal',
          options: [{ tr: 'Toplam on lira.', en: '', wrong: true }, { tr: 'Toplam yirmi lira.', en: '' }, { tr: 'Toplam yirmi beş lira.', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 4', activity: 'choice', optionsAreMeanings: true, say: '“ne kadar?” ne demek?', en: 'What does “ne kadar?” mean?', hint: 'Fiyatı sorarız.',
          options: [{ tr: 'how much?', en: '' }, { tr: 'where?', en: '', wrong: true }, { tr: 'who?', en: '', wrong: true }] },
        { type: 'exercise', title: 'Soru 5', activity: 'choice', say: 'Ekmek beş lira, süt on beş lira. Toplam ne kadar?', en: 'Bread is five lira, milk is fifteen lira. How much in total?', hint: '5 + 15 = 20 (yirmi)',
          options: [{ tr: 'On lira.', en: '', wrong: true }, { tr: 'Otuz lira.', en: '', wrong: true }, { tr: 'Yirmi lira.', en: '' }] },
        { type: 'exercise', title: 'Soru 6', activity: 'speak', say: 'Sesli söyle:', en: 'Say it out loud:', expect: ['Teşekkürler iyi günler', 'Teşekkür ederim iyi günler'], show: 'Teşekkürler, iyi günler!' },
      ],
    },
  ],
};
